### ISSUE TITLE
Deleting a post containing an Assigned task -> ERROR

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub-modules-tasks#47]
Stack Trace:

```
Error: Call to a member function createUrl() on null in protected/modules/tasks/models/Task.php:86
Stack trace:
#0 protected/humhub/modules/content/models/Content.php(367): humhub\modules\tasks\models\Task->getUrl()
#1 protected/humhub/components/SocialActivity.php(230): humhub\modules\content\models\Content->getUrl()
#2 protected/humhub/components/SocialActivity.php(148): humhub\components\SocialActivity->getUrl()
#3 protected/humhub/modules/notification/components/BaseNotification.php(113): humhub\components\SocialActivity->getViewParams(Array)
#4 protected/humhub/components/rendering/ViewPathRenderer.php(69): humhub\modules\notification\components\BaseNotification->getViewParams(Array)
#5 protected/humhub/modules/notification/targets/MailTarget.php(67): humhub\components\rendering\ViewPathRenderer->render(Object(humhub\modules\tasks\notifications\Assigned))
#6 protected/humhub/modules/notification/targets/BaseTarget.php(150): humhub\modules\notification\targets\MailTarget->handle(Object(humhub\modules\tasks\notifications\Assigned), Object(humhub\modules\user\models\User))
#7 protected/humhub/modules/notification/components/NotificationManager.php(107): humhub\modules\notification\targets\BaseTarget->send(Object(humhub\modules\tasks\notifications\Assigned), Object(humhub\modules\user\models\User))
#8 protected/humhub/modules/notification/jobs/SendNotification.php(37): humhub\modules\notification\components\NotificationManager->send(Object(humhub\modules\tasks\notifications\Assigned), Object(humhub\modules\user\models\User))
#9 protected/vendor/zhuravljov/yii2-queue/src/Queue.php(90): humhub\modules\notification\jobs\SendNotification->run()
#10 protected/vendor/zhuravljov/yii2-queue/src/sync/Driver.php(36): zhuravljov\yii\queue\Queue->run(Object(humhub\modules\notification\jobs\SendNotification))
#11 [internal function]: zhuravljov\yii\queue\sync\Driver->zhuravljov\yii\queue\sync\{closure}(Object(yii\base\Event))
#12 protected/vendor/yiisoft/yii2/base/Component.php(545): call_user_func(Object(Closure), Object(yii\base\Event))
#13 protected/vendor/yiisoft/yii2/base/Application.php(383): yii\base\Component->trigger('afterRequest')
#14 index.php(25): yii\base\Application->run()
#15 {main} 
```

If the Task is **NOT ASSIGNED**, no problem.

**Comment by Felli** [comment]
Hmm... I'm getting a somewhat different error... Which will cause a Notification what will break the Notifications and render them useless.
```
Error: Call to a member function getContentDescription() on null in /home/futayuri/SITE/protected/modules/tasks/notifications/Assigned.php:24 Stack trace:
#0 /home/USER/SITE/protected/humhub/components/SocialActivity.php(150): humhub\modules\tasks\notifications\Assigned->html()
#1 /home/USER/SITE/protected/humhub/modules/notification/components/BaseNotification.php(113): humhub\components\SocialActivity->getViewParams(Array)
#2 /home/USER/SITE/protected/humhub/components/rendering/ViewPathRenderer.php(69): humhub\modules\notification\components\BaseNotification->getViewParams(Array)
#3 /home/USER/SITE/protected/humhub/modules/notification/components/BaseNotification.php(322): humhub\components\rendering\ViewPathRenderer->render(Object(humhub\modules\tasks\notifications\Assigned))
#4 /home/USER/SITE/protected/humhub/modules/notification/controllers/ListController.php(47): humhub\modules\notification\components\BaseNotification->render()
#5 [internal function]: humhub\modules\notification\controllers\ListController->actionIndex()
#6 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#8 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('', Array)
#9 /home/USER/SITE/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('notification/li...', Array)
#10 /home/USER/SITE/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#11 /home/USER/SITE/index.php(25): yii\base\Application->run()
#12 {main}
```
